version: "3"
services:
  web:
    image: virtual-dash:dev
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    command: rails s -b 0.0.0.0
    links:
      - db
      - redis
    ports:
      - 3000:3000
    environment:
      - BUNDLE_PATH=/bundle/vendor
    volumes:
    - ./../:/home/virtual-dash/
    - node_modules_path:/home/virtual-dash/node_modules/
    - bundle_path:/bundle/
    environment:
    - RAILS_LOG_TO_STDOUT=true
    - POSTGRES_HOST=db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - STRAVA_CLIENT_ID=54154
    - STRAVA_CLIENT_SECRET=dc5d0e5fd37d42098944c0416ebc8eb203e25488
    - STRIPE_PUB_KEY=pk_test_51HNKEKLf04duTe6muNEmSQGfQl6V9JAMTemqXr7iCPQo2FMMBWND7PxK4bGVoWLywMN7nhf5v0zpq3MsMFcf4KBz00y8tkEnVS
    - STRIPE_SECRET_KEY=sk_test_51HNKEKLf04duTe6mJnC6JjjfcdZOhDOLpkH9jTR305WvYku3Qu8TTJvl0FZDVaCtRY9SiEIQqB9u07k7nb9S4W6i008aBuz03I
    - GMAPS_KEY=AIzaSyD1yemIABjJWJ13y1dNLnuGCVOHicAluk0
    - REDIS_URL=redis://redis:6379/1
    - MAILGUN_API_KEY=2f77f7446a98a7fbb58ce18953ea23b1-1d8af1f4-fed434fc
    - MAILGUN_API_DOMAIN=mg.vitualdash.co
  worker:
    image: virtual-dash:dev
    build:
      context: ./../
      dockerfile: ./docker/Dockerfile
    command: sidekiq -C config/sidekiq.yml
    links:
      - db
      - redis
    environment:
      - BUNDLE_PATH=/bundle/vendor
    volumes:
    - ./../:/home/virtual-dash/
    - node_modules_path:/home/virtual-dash/node_modules/
    - bundle_path:/bundle/
    environment:
    - RAILS_LOG_TO_STDOUT=true
    - POSTGRES_HOST=db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - STRAVA_CLIENT_ID=54154
    - STRAVA_CLIENT_SECRET=dc5d0e5fd37d42098944c0416ebc8eb203e25488
    - STRIPE_PUB_KEY=pk_test_51HNKEKLf04duTe6muNEmSQGfQl6V9JAMTemqXr7iCPQo2FMMBWND7PxK4bGVoWLywMN7nhf5v0zpq3MsMFcf4KBz00y8tkEnVS
    - STRIPE_SECRET_KEY=sk_test_51HNKEKLf04duTe6mJnC6JjjfcdZOhDOLpkH9jTR305WvYku3Qu8TTJvl0FZDVaCtRY9SiEIQqB9u07k7nb9S4W6i008aBuz03I
    - GMAPS_KEY=AIzaSyD1yemIABjJWJ13y1dNLnuGCVOHicAluk0
    - MAILGUN_API_KEY=2f77f7446a98a7fbb58ce18953ea23b1-1d8af1f4-fed434fc
    - MAILGUN_API_DOMAIN=mg.vitualdash.co
  db:
    image: "postgres:10.12"
    ports:
      - "5432:5432"
    environment:
    - POSTGRES_PASSWORD=password
    volumes:
      - virtual-dash_dbdata:/var/lib/postgresql/data
  redis:
    image: "redis:alpine"
    ports:
      - "0.0.0.0:6379:6379"
      # - "6379:6379"
volumes:
  bundle_path:
  node_modules_path:
  virtual-dash_dbdata:
