name: Deploy on Master
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_MAIN}}
          heroku_email: "victor@growthconstant.com"
      - name: DB Migrate w/ Heroku Run
        uses: michcio1234/heroku-run@0.1.1
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME_MAIN}}
          heroku_email: "victor@growthconstant.com"
          # Command to run.
          command: rake db:migrate